name: Build and Deploy to Huawei ECS

on:
  push:
    branches: [ master ]

env:
  FULL_IMAGE: swr.tr-west-1.myhuaweicloud.com/gorkem/listeraf:${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Huawei Cloud SWR
        run: echo "${{ secrets.SWR_PASSWORD }}" | docker login -u "${{ secrets.SWR_USERNAME }}" --password-stdin swr.tr-west-1.myhuaweicloud.com

      - name: Build Docker image
        run: docker build -t $FULL_IMAGE .

      - name: Push Docker image to SWR
        run: docker push $FULL_IMAGE

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ECS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ECS1_HOST }}
          username: ${{ secrets.ECS_USERNAME }}
          key: ${{ secrets.ECS_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.SWR_USERNAME }} -p ${{ secrets.SWR_PASSWORD }} swr.${{ secrets.SWR_REGION }}.myhuaweicloud.com

            docker pull $FULL_IMAGE

            docker stop myapp || true && docker rm myapp || true

            docker run -d --name myapp -p 80:3000 $FULL_IMAGE
